package com.api.stock.model;

public enum StatusPedido {
    PEDIDO_REALIZADO,
    PEDIDO_CONFIRMADO,
    NOTA_GERADA,
    PEDIDO_RECEBIDO,
    ENVIADO_TRANSPORTADORA,
    RECEBiDO_TRANSPORTADORA,
    MERCADORIA_TRANSITO,
    PEDIDO_ENTREGUE,
    PROBLEMA_ENTREGA,
    PROCESSO_DEVOLUCAO,
    PEDIDO_DEVOLVIDO,
    PEDIDO_CANCELADO
}
